<?xml version="1.0" encoding="utf-8"?><Database Name="cookies" Class="cookiesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\cookies.mdf;Integrated Security=True" SettingsObjectName="WindowsFormsApp15.Properties.Settings" SettingsPropertyName="cookiesConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Client" Member="Clients">
    <Type Name="Client">
      <Column Name="ClientID" Type="System.String" DbType="NChar(4) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ClientName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ClientPassword" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ClientPhone" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="Client_Order" Member="Orders" ThisKey="ClientID" OtherKey="ClientID" Type="Order" />
    </Type>
  </Table>
  <Table Name="dbo.Vegetable" Member="Vegetables">
    <Type Name="Vegetable">
      <Column Name="VegeID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="VegeName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="VegePricePerKG" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Vegetable_Vege_Order" Member="Vege_Orders" ThisKey="VegeID" OtherKey="VegeID" Type="Vege_Order" />
    </Type>
  </Table>
  <Table Name="dbo.[Order]" Member="Orders">
    <Type Name="Order">
      <Column Name="OrderID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ClientID" Type="System.String" DbType="NChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="OrderDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Payment" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Association Name="Order_Vege_Order" Member="Vege_Orders" ThisKey="OrderID" OtherKey="OrderID" Type="Vege_Order" />
      <Association Name="Client_Order" Member="Client" ThisKey="ClientID" OtherKey="ClientID" Type="Client" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Vege_Order" Member="Vege_Orders">
    <Type Name="Vege_Order">
      <Column Name="Vege_Order_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="VegeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OrderID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Unit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Association Name="Order_Vege_Order" Member="Order" ThisKey="OrderID" OtherKey="OrderID" Type="Order" IsForeignKey="true" />
      <Association Name="Vegetable_Vege_Order" Member="Vegetable" ThisKey="VegeID" OtherKey="VegeID" Type="Vegetable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Admin" Member="Admins">
    <Type Name="Admin">
      <Column Name="AdminName" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="AdminPass" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="AdminId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
</Database>